# Generated by Django 5.2.8 on 2025-11-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorApp', '0007_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='course_instance',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_instance',
            field=models.ManyToManyField(related_name='order', to='instructorApp.cart'),
        ),
    ]
